### ISSUE TITLE
Language dropdown based on question displayed

### ISSUE THREAD

**Issue by Ubayed-Bin-Sufian** [Ubayed-Bin-Sufian/Automatic-Code-Evaluator#8]
#### JSON file:
Need to add programming language based on the question

#### Target:
When any question gets displayed, the language dropdown would automatically toggle to the programming language from the JSON file for that specific question. 

#### How to do it:
1. Get the language from the JSON
2. Set in the variable

**Comment by abhijeet5ire** [comment]
@Ubayed-Bin-Sufian i have handle this issue in the PR need to make  basically we get the language from the json and set in the variable

**Comment by abhijeetsingh0401** [comment]
#13 fix this
